### ISSUE TITLE
さくらのVPNに木倉がアクセスできるようにする

### ISSUE THREAD

**Issue by Kiikurage** [HakabaV3/atami#5]
鍵を追加して欲しいです☆（ゝω・）vｷｬﾋﾟ

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGIPvIMZpyjnngiZi4F5bxkruRJ+4b+0ZChh9+fJCM07imiQC6UXWuzINlBL6fKwZOcv3W5+cNw5ikDLJ9PlqqfE/Tp6oo0d1lUjSQbIoHNjReIepM0qL12L/2qG//kEJBHDhZGk95aYUyCK3x3mgSoqEIBmJiaDHe4Af0rQ02//TDCz5/L4ZDOSAXmNsE0o4XyCUHoX+gT9t9PKJ9G1PPNTlHlrt3Ef8CQmFL7a8vlVgBNHp2bz5YZzoKlsdkW9zsw052CAR8WgyOhXBcUUem3EX4ij4TanxpB21I1b8l2H6iBJZgGQksmworjLRvBTkxGFQybueoiWW9GyVjv6Aj Kikurage@orenoMacBook-Air.local

**Comment by Dooor** [comment]
接続できましたよね？

**Comment by Dooor** [comment]
とじやす
